import { LegalCurrency } from './leagal-currency.model';

export const LEGAL_CURRENCIES: LegalCurrency[] = [
  {
    flagIconClass: 'fi fi-us',
    currencyName: 'USD',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '400807238',
    iban: '',
    sortCode: '',
    beneficiaryBankName: 'JP MORGAN CHASE BANK, New York',
    beneficiaryBankBic: 'CHASUS33',
    beneficiaryBankAddress: '383 Madison Avenue, New York, NY 10017, USA',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-eu',
    currencyName: 'EUR',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '5040040066',
    iban: 'DE05504000005040040066',
    sortCode: '',
    beneficiaryBankName: 'DEUTSCHE  BUNDESBANK, Frankfurt',
    beneficiaryBankBic: 'MARKDEFF',
    beneficiaryBankAddress:
      'Wilhelm-Epsteinn-Strabe 14, 60431 Frankfurt Am Main, Germany',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-gb',
    currencyName: 'GBP',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '40000982',
    iban: 'GB52CHAS60924280033041',
    sortCode: '60-92-42',
    beneficiaryBankName: 'JP MORGAN CHASE BANK NA, London',
    beneficiaryBankBic: 'CHASGB2L',
    beneficiaryBankAddress: '125 London Wall, London EC2Y 5AJ, UK',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-ch',
    currencyName: 'CHF',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '0700-01227572',
    iban: 'CH32 0070 0070 0012 2757 2',
    sortCode: '',
    beneficiaryBankName: 'ZURCHER KANTONALBANK, ZURICH',
    beneficiaryBankBic: 'ZKBKCHZZ80A',
    beneficiaryBankAddress: 'Josefstrasse 222, 8005 Zurich, Switzerland',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-au',
    currencyName: 'AUD',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '81753-2',
    iban: '',
    sortCode: '',
    beneficiaryBankName: 'RESERVE  BANK OF AUSTRALIA, Sydney',
    beneficiaryBankBic: 'RSBKAU2S',
    beneficiaryBankAddress: 'GPO Box 3947, Sydney NSW 2000, Australia',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-hk',
    currencyName: 'CNY',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '447-0-946243-6',
    iban: '',
    sortCode: '',
    beneficiaryBankName: 'STANDARD CHARTERED BANK, Hong Kong',
    beneficiaryBankBic: 'SCBLHKHH',
    beneficiaryBankAddress: 'GPO Box  21, Hong Kong',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-ca',
    currencyName: 'CAD',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '3144-1044-166',
    iban: '',
    sortCode: '',
    beneficiaryBankName: 'BANK OF MONTREAL, Toronto',
    beneficiaryBankBic: 'BOFMCAM2',
    beneficiaryBankAddress:
      '100 King Street West, 24th Floor, Toronto, Ontario, M5X 1A1, Canada',
    purposeOfPayment: 'for crediting account 47330992708',
  },
  {
    flagIconClass: 'fi fi-jp',
    currencyName: 'JPY',
    beneficiary: 'National Bank of Ukraine',
    beneficiaryBic: 'NBUA UA UX',
    beneficiaryAddress: '9 Instytutska St, Kyiv, 01601, Ukraine',
    accountNumber: '653-0430048',
    iban: '',
    sortCode: '',
    beneficiaryBankName: 'MUFG BANK LTD, Tokyo',
    beneficiaryBankBic: 'BOTK JP JT',
    beneficiaryBankAddress:
      '1-2-3, Nihombashi HONGOKU-CHO, Chuo-ku, Tokyo 1003 -0021 Japan',
    purposeOfPayment: 'for crediting account 47330992708',
  },
];

export const LEGAL_CURRENCY_LABELS: string[] = [
  'Flag',
  'Currency',
  'Account Number',
  'IBAN',
  'Sort Code',
  'Beneficiary Bank Name',
  'Beneficiary Bank BIC',
  'Beneficiary Bank Address',
  'Purpose of Payment',
  'Beneficiary',
  'Beneficiary Bic',
  'Beneficiary Address',
];
